<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2nd_ad</name>
   <tag></tag>
   <elementGuidId>8e5dc2f7-8c5b-4e6f-bf13-4594a08c1cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;product-info&quot;]/div[@class=&quot;item-title-wrap&quot;]/a[@data-p4p=&quot;true&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p4p']/div[2]/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;product-info&quot;]/div[@class=&quot;item-title-wrap&quot;]/a[@data-p4p=&quot;true&quot;])[2]</value>
   </webElementProperties>
</WebElementEntity>
